name: Create GitHub Release From Changelog
description: Creates a GitHub Release using Changelog file (based on Loren Segal's Action) - https://github.com/marketplace/actions/github-release-from-changelog
author: Loren Segal
branding:
  icon: award
  color: green
inputs:
  tag:
    description: The tag to use for the release. Omit if triggering from a tag event.
    required: false
    default: ${{ github.ref }}
  filename:
    description: Optional filename of changelog (default searches across a range of changelog filenames).
    required: false
    default: ""
  title:
    description: |
      Optional title formatting for release, defaults to "Release $tag".
      Use $tag as tag value.
    required: false
    default: Release $tag
  draft:
    description: Generate a draft release if true
    required: false
    default: "false"
  prerelease:
    description: Generate a pre-release if true
    required: false
    default: "false"
outputs:
  release_url:
    description: The GitHub release URL
    value: ${{ steps.main.outputs.release_url }}
  tag:
    description: The resolved tag name used by the action
    value: ${{ steps.main.outputs.tag }}
runs:
  using: "composite"
  steps:
    - run: ruby ${{ github.action_path }}/main.rb
      id: main
      shell: bash
